name: Update cache test

on: pull_request

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repo 
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - id: changed-files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        with:
         format: 'json'
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.all }}; do
            echo "$file was added"
          done