name: Invalidate cache

on: 
  push:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repo 
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
         format: 'csv'
      - name: Run cache invalidate script
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all }}
        run: tsx scripts/invalidateCache