name: Invalidate cache

on: pull_request

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repo 
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
         format: 'csv'
      - name: Run cache invalidate script
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all }}
        run: ts-node scripts/invalidateCache